### ISSUE TITLE
Error when mocking a query in a child component 

### ISSUE THREAD

**Issue by fl1p** [lifeiscontent/storybook-addon-apollo-client#44] opened 2021-08-04 16:31 UTC
or 

**How to mock an Apollo/GraphQL query in Storybook, when query is used in child component?**

I am trying to render a nextJS page component in Storybook. A child component of that page component is using a GraphQL query. I don't know if this is supposed to work at all, but when I mock that (child's) query in the story of the page component, I can see the mocked values in the console-like info section at the bottom of the screen in Storybook.

But I get an error:

    Uncaught Error: No more mocked responses for the query: query GetSidebarInfos($clientId: ID!, $walletId: ID!) {
      ..
    }

I am not sure where the ```__typename``` comes from, but I have read about it and providing a value for it in the mocked response didn't change anything.

Is it at all possible to mock nested queries like that?

**Comment by erwan-joly** [comment] 2022-08-12 08:28
@fl1p any details on this ? I'm facing the same problem but it seems like the issue is closed

**Comment by erwan-joly** [comment] 2022-08-12 08:41
@lifeiscontent I think this issue need to be reopened

**Comment by lifeiscontent** [comment] 2022-08-23 23:02
@erwan-joly can you provide a reproduction? I'll take a look at it when I can, or if you can submit a fix I can review, just ping me.

**Comment by erwan-joly** [comment] 2022-08-30 02:35
I tried to reproduce without success :/ will see if I can find some time to investigate what is really going on

**Comment by lifeiscontent** [comment] 2022-09-13 20:46
@erwan-joly okay, I'm going to close this issue, but if you can manage to reproduce it feel free to open another and I'll take a look.

**Closed by lifeiscontent** 2022-09-13 20:46 UTC
