### ISSUE TITLE
Storybook preview hooks can only be called inside decorators and story functions

### ISSUE THREAD

**Issue by petrbela** [lifeiscontent/storybook-addon-apollo-client#14] opened 2021-01-23 18:11 UTC
Not sure what I'm doing wrong but after upgrading to 4, I'm getting the following error:

```
Error: Storybook preview hooks can only be called inside decorators and story functions.
    at invalidHooksError (http://localhost:6006/vendors~main.9377cefe38073d45d22c.bundle.js:53512:10)
    at useStoryContext (http://localhost:6006/vendors~main.9377cefe38073d45d22c.bundle.js:53720:11)
    at Object.useParameter (http://localhost:6006/vendors~main.9377cefe38073d45d22c.bundle.js:53729:26)
    at WithApolloClient (http://localhost:6006/vendors~main.9377cefe38073d45d22c.bundle.js:655966:23)
    at http://localhost:6006/vendors~main.9377cefe38073d45d22c.bundle.js:53455:21
    at http://localhost:6006/vendors~main.9377cefe38073d45d22c.bundle.js:55247:12
    at http://localhost:6006/vendors~main.9377cefe38073d45d22c.bundle.js:55254:14
    at wrapper (http://localhost:6006/vendors~main.9377cefe38073d45d22c.bundle.js:44288:12)
    at http://localhost:6006/vendors~main.9377cefe38073d45d22c.bundle.js:53973:14
    at http://localhost:6006/vendors~main.9377cefe38073d45d22c.bundle.js:53987:26
```

Seems like it's the same issue as https://github.com/storybookjs/storybook/issues/9893 but has anyone run into this and figured out what exactly is causing it? I haven't had a problem with version 3 of this library.

**Comment by lifeiscontent** [comment] 2021-01-24 03:32
@petrbela what version are you using? do you have a reproduction I can look at?

**Comment by lifeiscontent** [comment] 2021-01-29 22:07
@petrbela can I close this issue? Or can you provide more information please?

**Comment by lifeiscontent** [comment] 2021-02-03 20:01
closing due to inactivity

**Comment by petrbela** [comment] 2021-02-03 20:44
Yeah sorry it's not a high enough priority for me right now, and my app uses 10+ addons so finding a minimal reproducible test case isn't trivial. I might get back to it later.

**Comment by lifeiscontent** [comment] 2021-02-03 21:53
@petrbela no worries at all, if you can share your storybook configs I can track it down if I can reproduce it using similar settings. if you could show me at least one story that would also help so I can know the shape of the code.

**Comment by afreeland** [comment] 2021-03-24 19:21
@lifeiscontent  Looks like I am seeing this issue as well
![image](https://user-images.githubusercontent.com/3135030/112370791-33715780-8cb4-11eb-9d37-e819491cd6d6.png)

_main.js_
```
module.exports = {
	stories: ['../src/**/*.stories.mdx', '../src/**/*.stories.@(js|jsx|ts|tsx)'],
	addons: [
		'@storybook/addon-links',
		'@storybook/addon-essentials',
		'@react-theming/storybook-addon',
		'storybook-addon-apollo-client',
	],
};
```

_preview.js_
```
import { MockedProvider } from '@apollo/client/testing'; // Use for Apollo Version 3+
import { ThemeProvider } from '@material-ui/core';
import { createMuiTheme } from '@material-ui/core/styles';
import { addDecorator } from '@storybook/react';
import { withThemes } from '@react-theming/storybook-addon';

import { themeConfig } from '../src/styles/theme';
// import '../src/styles/theme.css';

const providerFn = ({ theme, children }) => {
	const muTheme = createMuiTheme(themeConfig);
	return <ThemeProvider theme={muTheme}>{children}</ThemeProvider>;
};

// pass ThemeProvider and array of your themes to decorator
addDecorator(withThemes(null, [themeConfig], { providerFn }));

export const parameters = {
	actions: { argTypesRegex: '^on[A-Z].*' },
	apolloClient: {
		MockedProvider,
		// any props you want to pass to MockedProvider on every story
	},
	backgrounds: {
		default: 'cdp',
		values: [
			{
				name: 'cdp',
				value: themeConfig.palette.background.default,
			},
		],
	},
};

```

_component.stories.tsx_
```

export const Normal = Template.bind({});
Normal.args = {};
Normal.parameters = {
	apolloClient: {
		// do not put MockedProvider here, you can, but its preferred to do it in preview.js
		mocks: [
			{
				request: {
					query: AlertComments,
					variables: {
						alertId: 1,
					},
				},
				result: {
					data: {
						alertComments: {
							comment: 'Some random comment',
							id: 1,
						},
					},
				},
			},
		],
	},
};
```

**Comment by lifeiscontent** [comment] 2021-03-24 19:59
@afreeland thanks for the info! Would you be able to create a reproduction I can download and test with? Otherwise, if you're free, I'd be willing to pair with you on it to fix it!

**Comment by lifeiscontent** [comment] 2021-03-24 20:00
@afreeland do you have discord? maybe we could schedule something later today or sometime this week. lifeiscontent#6354

**Comment by afreeland** [comment] 2021-03-24 20:02
Would you be available to do a Google Hangout if I provide a link?  What time would be good for you, I am EST?

**Comment by lifeiscontent** [comment] 2021-03-24 20:03
I'm free after 6 PM PST, so anytime after that (weekdays). Not sure if that's too late for you, otherwise weekends are good. aaron@lifeiscontent.net

**Comment by afreeland** [comment] 2021-03-24 20:09
Sweet, just sent an invite.  Interested to see if we can figure it out...appreciate the quick response and help!

**Comment by lifeiscontent** [comment] 2021-03-25 16:49
CC: @petrbela

**Comment by HosseinAgha** [comment] 2021-04-17 12:49
I started getting this error when I updated storybook from 6.1 to 6.2

**Comment by lifeiscontent** [comment] 2021-04-18 16:43
@HosseinAgha given that you did an upgrade you might of installed multiple versions of Apollo. Do you use yarn or npm?

If you use yarn you can use the resolutions feature in package.json to force a specific version.

**Comment by lifeiscontent** [comment] 2021-04-28 22:42
https://github.com/lifeiscontent/storybook-addon-apollo-client/releases/tag/v4.0.8 Should fix these issues can any of you report back if the issues you were seeing are now solved with this new version?

@HosseinAgha @afreeland @petrbela

**Comment by lifeiscontent** [comment] 2021-05-18 23:51
Bump @petrbela @HosseinAgha

**Comment by boboci9** [comment] 2021-06-17 10:41
Hi @lifeiscontent,

I am having this exact same issue when trying to mock the apollo client for storybook using the storybook-addon-apollo-client version: "4.0.8"

<img width="891" alt="Screenshot 2021-06-17 at 13 41 13" src="https://user-images.githubusercontent.com/9323474/122381520-b3d0ed00-cf71-11eb-954c-441a20007da6.png">

<img width="1087" alt="Screenshot 2021-06-17 at 13 38 35" src="https://user-images.githubusercontent.com/9323474/122381319-75d3c900-cf71-11eb-9d19-05f7b77d9955.png">
<img width="1361" alt="Screenshot 2021-06-17 at 13 38 56" src="https://user-images.githubusercontent.com/9323474/122381323-779d8c80-cf71-11eb-85d7-7ec2859ac39c.png">

**Comment by lifeiscontent** [comment] 2021-06-17 21:26
@boboci9 do you have a reproduction that I can debug?

**Comment by lifeiscontent** [comment] 2021-08-06 07:53
closing due to inactivity

**Closed by lifeiscontent** 2021-08-06 07:53 UTC
Labels: needs more info
